Repository pickly-team/pickly-backend, pull requests merged in 2023-07, with the labels that each got.

#180 [fix]: 인자가 한 개인 생성자에 대한 역직렬화 오류 수정
  pickly-service/src/main/java/org/pickly/service/notification/controller/request/NotifyStandardDayUpdateReq.java
Labels: 🐛 Bug

#190 [Feat] 북마크 상세 조회 API 수정
  pickly-service/src/main/java/org/pickly/service/bookmark/common/BookmarkMapper.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/response/BookmarkRes.java
Labels: ✨ Feature

#187 [fix]: 알림 읽기 처리, 삭제 실제 반영 안되는 오류 수정
  pickly-service/src/main/java/org/pickly/service/notification/service/impl/NotificationServiceImpl.java
Labels: 🐛 Bug

#192 [Fix] 특정 유저 알림 내역 조회에 알림 생성시간 추가
  pickly-service/src/main/java/org/pickly/service/notification/common/NotificationMapper.java
  pickly-service/src/main/java/org/pickly/service/notification/controller/response/NotificationRes.java
  pickly-service/src/main/java/org/pickly/service/notification/service/dto/NotificationDTO.java
  pickly-service/src/main/java/org/pickly/service/notification/service/impl/NotificationServiceImpl.java
Labels: 🐛 Bug, ✨ Feature

#197 [BUG]: 댓글 수정 후 내용이 반영되지 않는 에러 수정
  pickly-service/src/main/java/org/pickly/service/comment/service/impl/CommentServiceImpl.java
Labels: 🐛 Bug, 😎 Self-Approve

#198 [BUG]: 팔로워, 팔로잉 리스트 조회 API res 수정
  pickly-service/src/main/java/org/pickly/service/friend/common/FriendMapper.java
  pickly-service/src/main/java/org/pickly/service/friend/controller/response/FollowerRes.java
  pickly-service/src/main/java/org/pickly/service/friend/controller/response/FollowingRes.java
  pickly-service/src/main/java/org/pickly/service/friend/service/dto/FollowerResDTO.java
  pickly-service/src/main/java/org/pickly/service/friend/service/dto/FollowingResDTO.java
Labels: 🐛 Bug

#165 [feat] 노말 알림 기능 구현
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkCreateReq.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkUpdateReq.java
  pickly-service/src/main/java/org/pickly/service/bookmark/repository/interfaces/BookmarkRepository.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/impl/BookmarkServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/interfaces/BookmarkService.java
  pickly-service/src/main/java/org/pickly/service/common/config/SecurityConfig.java
  pickly-service/src/main/java/org/pickly/service/common/filter/JwtFilter.java
  pickly-service/src/main/java/org/pickly/service/common/utils/validator/visibility/VisibilityCheck.java
  pickly-service/src/main/java/org/pickly/service/common/utils/validator/visibility/VisibilityValidator.java
  pickly-service/src/main/java/org/pickly/service/member/repository/impl/MemberQueryRepositoryImpl.java
  pickly-service/src/main/java/org/pickly/service/member/repository/interfaces/MemberQueryRepository.java
  pickly-service/src/main/java/org/pickly/service/member/service/impl/MemberServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/member/service/interfaces/MemberService.java
  pickly-service/src/main/java/org/pickly/service/notification/common/NotificationSender.java
  pickly-service/src/main/java/org/pickly/service/notification/entity/Notification.java
  pickly-service/src/main/java/org/pickly/service/notification/entity/NotificationTemplate.java
  pickly-service/src/main/java/org/pickly/service/notification/repository/impl/NotificationJdbcRepositoryImpl.java
  pickly-service/src/main/java/org/pickly/service/notification/repository/interfaces/NotificationJdbcRepository.java
  pickly-service/src/main/java/org/pickly/service/notification/repository/interfaces/NotificationRepository.java
  pickly-service/src/main/java/org/pickly/service/notification/repository/interfaces/NotificationTemplateRepository.java
  pickly-service/src/main/java/org/pickly/service/notification/scheduler/NotificationScheduler.java
  pickly-service/src/main/java/org/pickly/service/notification/service/impl/NotificationServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/notification/service/impl/NotificationTemplateServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/notification/service/interfaces/NotificationService.java
  pickly-service/src/main/java/org/pickly/service/notification/service/interfaces/NotificationTemplateService.java
  pickly-service/src/main/resources/data.sql
  pickly-service/src/main/resources/schema.sql
  pickly-service/src/test/groovy/org/pickly/service/notification/NotificationFactory.java
  pickly-service/src/test/resources/schema.sql
Labels: ✨ Feature, 🛠 Setting

#203 [BUG] swagger security 수정
  pickly-service/src/main/java/org/pickly/service/common/filter/JwtFilter.java
Labels: 🐛 Bug, 😎 Self-Approve

#205 [BUG] datasource timezone 지정
  pickly-service/src/main/resources/application-dev.yml
  pickly-service/src/main/resources/application-local.yml
Labels: 🐛 Bug, 🛠 Setting, 🗃 Database, 😎 Self-Approve

#212 [BUG] 북마크 추가 API가 정상적으로 동작하지 않는 이슈 수정
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkCreateReq.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkUpdateReq.java
  pickly-service/src/main/java/org/pickly/service/common/utils/validator/url/UrlValidator.java
  pickly-service/src/main/java/org/pickly/service/common/utils/validator/visibility/VisibilityCheck.java
  pickly-service/src/main/java/org/pickly/service/common/utils/validator/visibility/VisibilityValidator.java
Labels: 🐛 Bug, 😎 Self-Approve

#214 [Setting] 개발 DB의 sql init mode 옵션을 수정합니다.
  pickly-service/src/main/resources/application-dev.yml
Labels: 🗃 Database, 😎 Self-Approve

#218 [fix] 팔로잉 중 이거나, 팔로워를 차단해도 리스트에 계속나오는 문제를 해결합니다.
  pickly-service/src/main/java/org/pickly/service/block/service/impl/BlockServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/friend/service/impl/FriendServiceImpl.java
Labels: 🐛 Bug

#220 [feat] 유저 nickname 최대 길이 변경
  pickly-service/src/main/java/org/pickly/service/member/controller/request/MemberProfileUpdateReq.java
Labels: ✨ Feature, 😎 Self-Approve

#223 [feat] 멤버 알림 설정 API에 fcm Token 추가
  pickly-service/src/main/java/org/pickly/service/member/controller/MemberController.java
  pickly-service/src/main/java/org/pickly/service/member/controller/request/NotificationSettingsUpdateReq.java
  pickly-service/src/main/java/org/pickly/service/member/service/impl/MemberServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/member/service/interfaces/MemberService.java
Labels: ✨ Feature, 😎 Self-Approve

#232 [fix]: 북마크 읽음 상태가 작성자만 바뀌도록 수정
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/BookmarkController.java
  pickly-service/src/main/java/org/pickly/service/bookmark/repository/interfaces/BookmarkRepository.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/impl/BookmarkServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/interfaces/BookmarkService.java
Labels: 🐛 Bug, 😎 Self-Approve

#237 [BUG] 특정 멤버의 알림 내역 조회 API 수정
  pickly-service/src/main/java/org/pickly/service/notification/repository/interfaces/NotificationRepository.java
Labels: 🐛 Bug, 😎 Self-Approve
