Repository pickly-team/pickly-backend, pull requests merged in 2023-05, with the labels that each got.

#121 refactor: bookmark 생성필드 수정
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkCreateReq.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/impl/BookmarkServiceImpl.java
Labels: 🐛 Bug

#127 fix: 카테고리 리스트 페이징 오류 수정
  pickly-service/src/main/java/org/pickly/service/category/controller/CategoryController.java
  pickly-service/src/main/java/org/pickly/service/category/service/impl/CategoryServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/category/service/interfaces/CategoryService.java
Labels: 🐛 Bug

#144 [hotfix] block controller 내 parameter내의 blocker 문법 오류를 수정합니다.
  pickly-service/src/main/java/org/pickly/service/block/controller/BlockController.java
Labels: 🐛 Bug

#147 [CI / CD] 환경변수 세팅을 변경합니다.
  .github/workflows/gradle.yml
Labels: 🚀 CI/CD

#155 [Bug] Cors 설정 오류
  pickly-service/src/main/java/org/pickly/service/common/config/SecurityConfig.java
  pickly-service/src/main/java/org/pickly/service/common/filter/CorsWebFilter.java
Labels: 🐛 Bug, ✨ Feature, 🛠 Setting

#156 [Bug]: Swagger의 기본 요청이 http 입니다
  pickly-service/src/main/java/org/pickly/service/common/config/SwaggerConfig.java
Labels: 🐛 Bug, 📝 Docs
