Repository pickly-team/pickly-backend, pull requests merged in 2023-03, with the labels that each got.

#45 [feat] 친구 팔로우 & 언팔로우
  pickly-common/src/main/java/org/pickly/common/error/exception/ErrorCode.java
  pickly-service/src/main/java/org/pickly/service/friend/controller/FriendController.java
  pickly-service/src/main/java/org/pickly/service/friend/repository/interfaces/FriendRepository.java
  pickly-service/src/main/java/org/pickly/service/friend/service/impl/FriendServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/friend/service/interfaces/FriendService.java
  pickly-service/src/main/java/org/pickly/service/member/service/impl/MemberServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/member/service/interfaces/MemberService.java
Labels: ✨ Feature

#38 [feat] 특정 유저의 북마크 조회 관련
  build.gradle
  pickly-common/src/main/java/org/pickly/common/error/GlobalExceptionHandler.java
  pickly-service/src/main/java/org/pickly/service/ServiceApplication.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/BookmarkController.java
  pickly-service/src/main/java/org/pickly/service/bookmark/dto/service/BookmarkDTO.java
  pickly-service/src/main/java/org/pickly/service/bookmark/dto/service/BookmarkItemDTO.java
  pickly-service/src/main/java/org/pickly/service/bookmark/dto/service/BookmarkPreviewItemDTO.java
  pickly-service/src/main/java/org/pickly/service/bookmark/entity/Bookmark.java
  pickly-service/src/main/java/org/pickly/service/bookmark/repository/impl/BookmarkQueryRepositoryImpl.java
  pickly-service/src/main/java/org/pickly/service/bookmark/repository/interfaces/BookmarkQueryRepository.java
  pickly-service/src/main/java/org/pickly/service/bookmark/repository/interfaces/BookmarkRepository.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/impl/BookmarkServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/interfaces/BookmarkService.java
  pickly-service/src/main/java/org/pickly/service/comment/repository/impl/CommentQueryRepositoryImpl.java
  pickly-service/src/main/java/org/pickly/service/comment/repository/interfaces/CommentQueryRepository.java
  pickly-service/src/main/java/org/pickly/service/common/config/QueryDslConfig.java
  pickly-service/src/main/java/org/pickly/service/common/utils/page/PageRequest.java
  pickly-service/src/main/java/org/pickly/service/common/utils/page/PageResponse.java
  pickly-service/src/main/java/org/pickly/service/member/controller/MemberController.java
  pickly-service/src/main/java/org/pickly/service/member/entity/Member.java
  pickly-service/src/main/java/org/pickly/service/member/service/impl/MemberServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/member/service/interfaces/MemberService.java
  pickly-service/src/main/resources/application-local.yml
  pickly-service/src/main/resources/data.sql
  pickly-service/src/main/resources/schema.sql
  pickly-service/src/test/groovy/org/pickly/service/bookmark/BookmarkFactory.java
  pickly-service/src/test/groovy/org/pickly/service/bookmark/services/BookmarkServiceSpec.groovy
  pickly-service/src/test/groovy/org/pickly/service/category/CategoryFactory.java
  pickly-service/src/test/groovy/org/pickly/service/member/MemberFactory.java
Labels: ✨ Feature, 🛠 Setting

#62 GitHub Actions로 checkstyle CI를 추가합니다.
  .github/workflows/ci.yaml
Labels: 🛠 Setting, ✅ Test

#76 [feat] test profile 추가
  pickly-service/src/main/resources/application-test.yml
Labels: 🛠 Setting, 🗃 Database, 😎 Self-Approve

#86 CheckStyle CI를 제거합니다.
  .github/workflows/ci.yaml
Labels: 🛠 Setting

#85 [feat] 유저 모드 정보 조회
  pickly-service/src/main/java/org/pickly/service/member/common/MemberMapper.java
  pickly-service/src/main/java/org/pickly/service/member/controller/MemberController.java
  pickly-service/src/main/java/org/pickly/service/member/controller/response/MemberModeRes.java
  pickly-service/src/main/java/org/pickly/service/member/service/dto/MemberModeDTO.java
  pickly-service/src/main/java/org/pickly/service/member/service/impl/MemberServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/member/service/interfaces/MemberService.java
  pickly-service/src/main/java/org/pickly/service/notification/entity/NotificationStandard.java
  pickly-service/src/main/java/org/pickly/service/notification/repository/interfaces/NotificationStandardRepository.java
  pickly-service/src/main/java/org/pickly/service/notification/service/impl/NotificationStandardServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/notification/service/interfaces/NotificationStandardService.java
  pickly-service/src/main/resources/data.sql
  pickly-service/src/main/resources/schema.sql
Labels: ✨ Feature, 🗃 Database

#80 [feat] 로그인 유저의 Comment 조회 관련
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/BookmarkController.java
  pickly-service/src/main/java/org/pickly/service/bookmark/repository/interfaces/BookmarkRepository.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/impl/BookmarkServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/interfaces/BookmarkService.java
  pickly-service/src/main/java/org/pickly/service/comment/controller/CommentController.java
  pickly-service/src/main/java/org/pickly/service/comment/controller/response/CommentRes.java
  pickly-service/src/main/java/org/pickly/service/comment/repository/impl/CommentQueryRepositoryImpl.java
  pickly-service/src/main/java/org/pickly/service/comment/repository/interfaces/CommentQueryRepository.java
  pickly-service/src/main/java/org/pickly/service/comment/repository/interfaces/CommentRepository.java
  pickly-service/src/main/java/org/pickly/service/comment/service/dto/CommentDTO.java
  pickly-service/src/main/java/org/pickly/service/comment/service/impl/CommentServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/comment/service/interfaces/CommentService.java
Labels: ✨ Feature

#92 [setting] github action CI workflow 추가
  .github/workflows/test.yml
  pickly-service/build.gradle
  pickly-service/src/main/resources/application-test.yml
  pickly-service/src/test/groovy/org/pickly/service/TestConfig.groovy
  pickly-service/src/test/groovy/org/pickly/service/bookmark/services/BookmarkServiceSpec.groovy
  pickly-service/src/test/groovy/org/pickly/service/friend/service/FriendServiceSpec.groovy
  pickly-service/src/test/groovy/org/pickly/service/member/service/MemberServiceSpec.groovy
  pickly-service/src/test/groovy/org/pickly/service/spock/CustomStringUtilTest.groovy
  pickly-service/src/test/resources/schema.sql
Labels: 🛠 Setting, ✅ Test

#60 [feat] 북마크 즐겨찾기 단일 삭제 및 일괄 삭제 API 추가
  pickly-service/src/main/java/org/pickly/service/bookmark/common/BookmarkMapper.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/BookmarkController.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkDeleteReq.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkDeleteRes.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkListDeleteReq.java
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/request/BookmarkListDeleteRes.java
  pickly-service/src/main/java/org/pickly/service/bookmark/repository/interfaces/BookmarkRepository.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/dto/BookmarkDeleteReqDTO.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/dto/BookmarkDeleteResDTO.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/dto/BookmarkListDeleteReqDTO.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/dto/BookmarkListDeleteResDTO.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/impl/BookmarkServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/bookmark/service/interfaces/BookmarkService.java
Labels: ✨ Feature
