Repository pickly-team/pickly-backend, pull requests merged in 2023-04, with the labels that each got.

#106 [hotfix] version 어노테이션으로 인한 swagger 접속 이슈를 해결합니다.
  pickly-service/src/main/java/org/pickly/service/common/config/WebConfig.java
Labels: 🐛 Bug

#111 [setting] CI / CD 시도시 profile 설정이 Local로 바라보고있는 docker설정을 dev로 변경합니다.
  pickly-service/Dockerfile
Labels: ❗️invalid

#114 [feat] 알림 기준 설정 API를 추가합니다.
  pickly-service/src/main/java/org/pickly/service/member/common/MemberMapper.java
  pickly-service/src/main/java/org/pickly/service/member/controller/response/MemberModeRes.java
  pickly-service/src/main/java/org/pickly/service/member/service/dto/MemberModeDTO.java
  pickly-service/src/main/java/org/pickly/service/member/service/impl/MemberServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/notification/controller/NotificationStandardController.java
  pickly-service/src/main/java/org/pickly/service/notification/controller/request/NotificationStandardCreateReq.java
  pickly-service/src/main/java/org/pickly/service/notification/controller/request/NotificationStandardUpdateReq.java
  pickly-service/src/main/java/org/pickly/service/notification/controller/response/NotificationStandardRes.java
  pickly-service/src/main/java/org/pickly/service/notification/entity/NotificationStandard.java
  pickly-service/src/main/java/org/pickly/service/notification/mapper/NotificationStandardMapper.java
  pickly-service/src/main/java/org/pickly/service/notification/repository/interfaces/NotificationStandardRepository.java
  pickly-service/src/main/java/org/pickly/service/notification/service/dto/NotificationStandardDTO.java
  pickly-service/src/main/java/org/pickly/service/notification/service/impl/NotificationStandardServiceImpl.java
  pickly-service/src/main/java/org/pickly/service/notification/service/interfaces/NotificationStandardService.java
  pickly-service/src/main/resources/data.sql
  pickly-service/src/main/resources/schema.sql
  pickly-service/src/test/groovy/org/pickly/service/notification/NotificationStandardFactory.java
  pickly-service/src/test/groovy/org/pickly/service/notification/service/NotificationStandardServiceSpec.groovy
  pickly-service/src/test/resources/schema.sql
Labels: ✨ Feature

#119 [refactor] custom paging 관련 API spec 변경
  pickly-service/src/main/java/org/pickly/service/bookmark/controller/BookmarkController.java
  pickly-service/src/main/resources/schema.sql
  pickly-service/src/test/resources/schema.sql
Labels: 🐛 Bug, ♻️ Refactor
